=== JoaquinSiabra/curso-JAX-WS/E4-EjemploXML-Validacion/src/envio.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2010 rel. 2 (http://www.altova.com) by IGAE Intervenci贸n Gral. de la Adm贸n. Del Estado (IGAE Intervenci贸n Gral. de la Adm贸n. Del Estado) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="Raiz">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Cabecera">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="NumCOE"/>
							<xs:element name="Anualidad"/>
							<xs:element name="FechaEnvio"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="DocumentoContable">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Cabecera">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="NumOficinaContable"/>
										<xs:element name="NumCOE"/>
										<xs:element name="Ejercicio"/>
										<xs:element name="NumIdTelcon"/>
										<xs:element name="NumAplicaciones"/>
										<xs:element name="CodigoMC"/>
										<xs:element name="DigitoSigno"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Cuerpo">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="NumExpediente"/>
										<xs:element name="Seccion"/>
										<xs:element name="Modificaciones">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence maxOccurs="unbounded">
														<xs:element name="Modificacion">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="Servicio"/>
																	<xs:element name="PorPrograma"/>
																	<xs:element name="Economica"/>
																	<xs:element name="CodModificacion"/>
																	<xs:element name="Importe"/>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
													</xs:sequence>
													<xs:element name="ImporteTotal"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== JoaquinSiabra/curso-JAX-WS/E4-EjemploXML-Validacion/src/envio.xml
<?xml version="1.0" encoding="UTF-8"?>
<Raiz xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="envio.xsd">
	<Cabecera>
		<NumCOE>02160001</NumCOE>
		<Anualidad>2009</Anualidad>
		<FechaEnvio>15/10/2009</FechaEnvio>
	</Cabecera>
	<DocumentoContable>
		<Cabecera>
			<NumOficinaContable>00160</NumOficinaContable>
			<NumCOE>0216001</NumCOE>
			<Ejercicio>2009</Ejercicio>
			<NumIdTelcon>0000000000421</NumIdTelcon>
			<NumAplicaciones>2</NumAplicaciones>
			<CodigoMC>080</CodigoMC>
			<DigitoSigno>0</DigitoSigno>
		</Cabecera>
		<Cuerpo>
			<NumExpediente>65</NumExpediente>
			<Seccion>15</Seccion>
			<Modificaciones>
				<Modificacion>
					<Servicio>014</Servicio>
					<PorPrograma>931N</PorPrograma>
					<Economica>100</Economica>
					<CodModificacion>75</CodModificacion>
					<Importe>2800</Importe>
				</Modificacion>
				<Modificacion>
					<Servicio>014</Servicio>
					<PorPrograma>931N</PorPrograma>
					<Economica>120</Economica>
					<CodModificacion>75</CodModificacion>
					<Importe>3300</Importe>
				</Modificacion>
				<ImporteTotal>6100</ImporteTotal>
			</Modificaciones>
		</Cuerpo>
	</DocumentoContable>
</Raiz>
